// <auto-generated />
using System;
using FitnessTracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FitnessTracker.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20201204120715_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("FitnessTracker.Models.Coach", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GoalId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.HasIndex("GoalId");

                    b.ToTable("Coach");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "coach_1@example.com",
                            GoalId = 1,
                            Name = "CoachName_1",
                            Phone = "123456789",
                            Surname = "CoachSurname_1"
                        },
                        new
                        {
                            Id = 2,
                            Email = "coach_2@example.com",
                            GoalId = 2,
                            Name = "CoachName_2",
                            Phone = "987654321",
                            Surname = "CoachSurname_2"
                        });
                });

            modelBuilder.Entity("FitnessTracker.Models.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("Czas")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("Dystans")
                        .HasColumnType("int");

                    b.Property<int?>("GoalId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("Obciazenie")
                        .HasColumnType("int");

                    b.Property<int?>("Powtorzenia")
                        .HasColumnType("int");

                    b.Property<int?>("Serie")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GoalId");

                    b.ToTable("Exercise");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GoalId = 1,
                            Name = "Przysiad ze sztangą",
                            Powtorzenia = 8,
                            Serie = 4
                        },
                        new
                        {
                            Id = 2,
                            GoalId = 3,
                            Name = "Wykroki ze sztangielkami",
                            Powtorzenia = 8,
                            Serie = 4
                        },
                        new
                        {
                            Id = 3,
                            GoalId = 3,
                            Name = "Przysiad w szerokim rozkroku",
                            Powtorzenia = 8,
                            Serie = 4
                        },
                        new
                        {
                            Id = 4,
                            GoalId = 3,
                            Name = "Wyciskanie sztangielek w pozycji leżącej",
                            Powtorzenia = 12,
                            Serie = 3
                        },
                        new
                        {
                            Id = 5,
                            GoalId = 3,
                            Name = "Brzuszki z nogami uniesionymi",
                            Powtorzenia = 25,
                            Serie = 3
                        },
                        new
                        {
                            Id = 6,
                            GoalId = 3,
                            Name = "Brzuszki skośne",
                            Powtorzenia = 25,
                            Serie = 3
                        },
                        new
                        {
                            Id = 7,
                            Czas = 30,
                            GoalId = 3,
                            Name = "Plank",
                            Serie = 3
                        });
                });

            modelBuilder.Entity("FitnessTracker.Models.ExerciseHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("Date")
                        .HasColumnType("Date");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("ExerciseId", "UserId", "Date")
                        .IsUnique();

                    b.ToTable("ExerciseHistory");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2020, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExerciseId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2020, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExerciseId = 2,
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2020, 12, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExerciseId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2020, 12, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExerciseId = 2,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("FitnessTracker.Models.ExerciseHistoryStats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("Czas")
                        .HasColumnType("int");

                    b.Property<int?>("Dystans")
                        .HasColumnType("int");

                    b.Property<int>("ExerciseHistoryId")
                        .HasColumnType("int");

                    b.Property<int?>("Obciazenie")
                        .HasColumnType("int");

                    b.Property<int?>("Powtorzenia")
                        .HasColumnType("int");

                    b.Property<int?>("Serie")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseHistoryId");

                    b.ToTable("ExerciseHistoryStats");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExerciseHistoryId = 1,
                            Powtorzenia = 1,
                            Serie = 1
                        },
                        new
                        {
                            Id = 2,
                            ExerciseHistoryId = 1,
                            Powtorzenia = 4,
                            Serie = 2
                        },
                        new
                        {
                            Id = 3,
                            ExerciseHistoryId = 1,
                            Powtorzenia = 6,
                            Serie = 3
                        },
                        new
                        {
                            Id = 4,
                            ExerciseHistoryId = 2,
                            Powtorzenia = 3,
                            Serie = 1
                        },
                        new
                        {
                            Id = 5,
                            ExerciseHistoryId = 2,
                            Powtorzenia = 6,
                            Serie = 2
                        },
                        new
                        {
                            Id = 6,
                            ExerciseHistoryId = 2,
                            Powtorzenia = 8,
                            Serie = 3
                        },
                        new
                        {
                            Id = 7,
                            ExerciseHistoryId = 3,
                            Powtorzenia = 9,
                            Serie = 7
                        },
                        new
                        {
                            Id = 8,
                            ExerciseHistoryId = 3,
                            Powtorzenia = 2,
                            Serie = 2
                        },
                        new
                        {
                            Id = 9,
                            ExerciseHistoryId = 4,
                            Powtorzenia = 1,
                            Serie = 8
                        },
                        new
                        {
                            Id = 10,
                            ExerciseHistoryId = 4,
                            Powtorzenia = 5,
                            Serie = 4
                        });
                });

            modelBuilder.Entity("FitnessTracker.Models.Goal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Goal");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Redukcja tkanki tłuszczowej"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Przybranie masy mięśniowej"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Rekompozycja sylwetki"
                        });
                });

            modelBuilder.Entity("FitnessTracker.Models.RefreshToken", b =>
                {
                    b.Property<string>("Token")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpireDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Invalidated")
                        .HasColumnType("bit");

                    b.Property<string>("JwtId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Used")
                        .HasColumnType("bit");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Token");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("FitnessTracker.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Moderator"
                        },
                        new
                        {
                            Id = 3,
                            Name = "User"
                        });
                });

            modelBuilder.Entity("FitnessTracker.Models.Training", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Training");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsPublic = true,
                            Name = "Trening_Publiczny_1"
                        },
                        new
                        {
                            Id = 2,
                            IsPublic = false,
                            Name = "Trening_Prywatny_1"
                        },
                        new
                        {
                            Id = 3,
                            IsPublic = false,
                            Name = "Trening_Prywatny_2"
                        },
                        new
                        {
                            Id = 4,
                            IsPublic = true,
                            Name = "Trening_Publiczny_2"
                        });
                });

            modelBuilder.Entity("FitnessTracker.Models.TrainingExercise", b =>
                {
                    b.Property<int>("ExerciseId")
                        .HasColumnType("int");

                    b.Property<int>("TrainingId")
                        .HasColumnType("int");

                    b.HasKey("ExerciseId", "TrainingId");

                    b.HasIndex("TrainingId");

                    b.ToTable("TrainingExercise");

                    b.HasData(
                        new
                        {
                            ExerciseId = 1,
                            TrainingId = 1
                        },
                        new
                        {
                            ExerciseId = 2,
                            TrainingId = 1
                        },
                        new
                        {
                            ExerciseId = 3,
                            TrainingId = 1
                        },
                        new
                        {
                            ExerciseId = 4,
                            TrainingId = 1
                        },
                        new
                        {
                            ExerciseId = 1,
                            TrainingId = 2
                        },
                        new
                        {
                            ExerciseId = 5,
                            TrainingId = 2
                        },
                        new
                        {
                            ExerciseId = 6,
                            TrainingId = 2
                        },
                        new
                        {
                            ExerciseId = 1,
                            TrainingId = 3
                        },
                        new
                        {
                            ExerciseId = 2,
                            TrainingId = 3
                        },
                        new
                        {
                            ExerciseId = 6,
                            TrainingId = 3
                        },
                        new
                        {
                            ExerciseId = 7,
                            TrainingId = 3
                        },
                        new
                        {
                            ExerciseId = 4,
                            TrainingId = 4
                        },
                        new
                        {
                            ExerciseId = 3,
                            TrainingId = 4
                        },
                        new
                        {
                            ExerciseId = 2,
                            TrainingId = 4
                        },
                        new
                        {
                            ExerciseId = 5,
                            TrainingId = 4
                        });
                });

            modelBuilder.Entity("FitnessTracker.Models.TrainingHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("Date")
                        .HasColumnType("Date");

                    b.Property<int>("TrainingId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TrainingId");

                    b.HasIndex("UserId");

                    b.ToTable("TrainingHistory");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2020, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrainingId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2020, 12, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrainingId = 2,
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2020, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrainingId = 3,
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2020, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrainingId = 3,
                            UserId = 2
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateTime(2020, 12, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrainingId = 3,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("FitnessTracker.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int?>("GoalId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.HasIndex("GoalId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@gmail.com",
                            GoalId = 2,
                            Name = "Admin Name",
                            PasswordHash = new byte[] { 224, 233, 64, 141, 111, 254, 250, 42, 31, 11, 216, 163, 185, 233, 2, 253, 18, 145, 154, 67, 33, 203, 57, 76, 203, 153, 231, 38, 93, 172, 117, 2, 166, 191, 204, 142, 188, 169, 8, 170, 39, 72, 93, 100, 172, 102, 211, 201, 20, 102, 72, 207, 30, 120, 211, 47, 251, 92, 149, 165, 247, 232, 177, 202 },
                            PasswordSalt = new byte[] { 237, 18, 4, 250, 240, 113, 136, 55, 251, 2, 164, 219, 60, 187, 47, 106, 18, 27, 43, 86, 82, 115, 187, 119, 182, 129, 111, 5, 205, 249, 162, 217, 43, 118, 181, 79, 89, 212, 30, 200, 70, 233, 23, 12, 56, 49, 8, 25, 36, 73, 113, 206, 107, 171, 11, 212, 15, 162, 213, 1, 102, 60, 188, 44, 252, 50, 195, 123, 83, 31, 229, 209, 247, 57, 137, 222, 212, 178, 131, 108, 212, 118, 85, 178, 3, 90, 230, 210, 15, 68, 241, 253, 80, 188, 94, 173, 91, 206, 173, 219, 151, 42, 110, 77, 44, 209, 13, 167, 10, 86, 143, 88, 116, 234, 190, 226, 35, 177, 211, 127, 8, 148, 235, 153, 76, 197, 68, 6 },
                            RoleId = 1,
                            Surname = "Admin Surname"
                        },
                        new
                        {
                            Id = 2,
                            Email = "moderator@gmail.com",
                            GoalId = 3,
                            Name = "Moderator Name",
                            PasswordHash = new byte[] { 224, 233, 64, 141, 111, 254, 250, 42, 31, 11, 216, 163, 185, 233, 2, 253, 18, 145, 154, 67, 33, 203, 57, 76, 203, 153, 231, 38, 93, 172, 117, 2, 166, 191, 204, 142, 188, 169, 8, 170, 39, 72, 93, 100, 172, 102, 211, 201, 20, 102, 72, 207, 30, 120, 211, 47, 251, 92, 149, 165, 247, 232, 177, 202 },
                            PasswordSalt = new byte[] { 237, 18, 4, 250, 240, 113, 136, 55, 251, 2, 164, 219, 60, 187, 47, 106, 18, 27, 43, 86, 82, 115, 187, 119, 182, 129, 111, 5, 205, 249, 162, 217, 43, 118, 181, 79, 89, 212, 30, 200, 70, 233, 23, 12, 56, 49, 8, 25, 36, 73, 113, 206, 107, 171, 11, 212, 15, 162, 213, 1, 102, 60, 188, 44, 252, 50, 195, 123, 83, 31, 229, 209, 247, 57, 137, 222, 212, 178, 131, 108, 212, 118, 85, 178, 3, 90, 230, 210, 15, 68, 241, 253, 80, 188, 94, 173, 91, 206, 173, 219, 151, 42, 110, 77, 44, 209, 13, 167, 10, 86, 143, 88, 116, 234, 190, 226, 35, 177, 211, 127, 8, 148, 235, 153, 76, 197, 68, 6 },
                            RoleId = 2,
                            Surname = "Moderator Surname"
                        },
                        new
                        {
                            Id = 3,
                            Email = "user@gmail.com",
                            GoalId = 1,
                            Name = "User Name",
                            PasswordHash = new byte[] { 224, 233, 64, 141, 111, 254, 250, 42, 31, 11, 216, 163, 185, 233, 2, 253, 18, 145, 154, 67, 33, 203, 57, 76, 203, 153, 231, 38, 93, 172, 117, 2, 166, 191, 204, 142, 188, 169, 8, 170, 39, 72, 93, 100, 172, 102, 211, 201, 20, 102, 72, 207, 30, 120, 211, 47, 251, 92, 149, 165, 247, 232, 177, 202 },
                            PasswordSalt = new byte[] { 237, 18, 4, 250, 240, 113, 136, 55, 251, 2, 164, 219, 60, 187, 47, 106, 18, 27, 43, 86, 82, 115, 187, 119, 182, 129, 111, 5, 205, 249, 162, 217, 43, 118, 181, 79, 89, 212, 30, 200, 70, 233, 23, 12, 56, 49, 8, 25, 36, 73, 113, 206, 107, 171, 11, 212, 15, 162, 213, 1, 102, 60, 188, 44, 252, 50, 195, 123, 83, 31, 229, 209, 247, 57, 137, 222, 212, 178, 131, 108, 212, 118, 85, 178, 3, 90, 230, 210, 15, 68, 241, 253, 80, 188, 94, 173, 91, 206, 173, 219, 151, 42, 110, 77, 44, 209, 13, 167, 10, 86, 143, 88, 116, 234, 190, 226, 35, 177, 211, 127, 8, 148, 235, 153, 76, 197, 68, 6 },
                            RoleId = 3,
                            Surname = "User Surname"
                        });
                });

            modelBuilder.Entity("FitnessTracker.Models.UserTraining", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("TrainingId")
                        .HasColumnType("int");

                    b.Property<bool>("Favourite")
                        .HasColumnType("bit");

                    b.HasKey("UserId", "TrainingId");

                    b.HasIndex("TrainingId");

                    b.ToTable("UserTraining");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            TrainingId = 1,
                            Favourite = false
                        },
                        new
                        {
                            UserId = 1,
                            TrainingId = 2,
                            Favourite = false
                        },
                        new
                        {
                            UserId = 1,
                            TrainingId = 3,
                            Favourite = true
                        },
                        new
                        {
                            UserId = 2,
                            TrainingId = 3,
                            Favourite = false
                        },
                        new
                        {
                            UserId = 3,
                            TrainingId = 3,
                            Favourite = false
                        },
                        new
                        {
                            UserId = 3,
                            TrainingId = 4,
                            Favourite = true
                        });
                });

            modelBuilder.Entity("FitnessTracker.Models.Coach", b =>
                {
                    b.HasOne("FitnessTracker.Models.Goal", "Goal")
                        .WithMany()
                        .HasForeignKey("GoalId");

                    b.Navigation("Goal");
                });

            modelBuilder.Entity("FitnessTracker.Models.Exercise", b =>
                {
                    b.HasOne("FitnessTracker.Models.Goal", "Goal")
                        .WithMany()
                        .HasForeignKey("GoalId");

                    b.Navigation("Goal");
                });

            modelBuilder.Entity("FitnessTracker.Models.ExerciseHistory", b =>
                {
                    b.HasOne("FitnessTracker.Models.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitnessTracker.Models.User", null)
                        .WithMany("ExerciseHistories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");
                });

            modelBuilder.Entity("FitnessTracker.Models.ExerciseHistoryStats", b =>
                {
                    b.HasOne("FitnessTracker.Models.ExerciseHistory", null)
                        .WithMany("ExerciseHistoryStats")
                        .HasForeignKey("ExerciseHistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FitnessTracker.Models.RefreshToken", b =>
                {
                    b.HasOne("FitnessTracker.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitnessTracker.Models.TrainingExercise", b =>
                {
                    b.HasOne("FitnessTracker.Models.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitnessTracker.Models.Training", "Training")
                        .WithMany()
                        .HasForeignKey("TrainingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("Training");
                });

            modelBuilder.Entity("FitnessTracker.Models.TrainingHistory", b =>
                {
                    b.HasOne("FitnessTracker.Models.Training", "Training")
                        .WithMany()
                        .HasForeignKey("TrainingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitnessTracker.Models.User", null)
                        .WithMany("TrainingHistories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Training");
                });

            modelBuilder.Entity("FitnessTracker.Models.User", b =>
                {
                    b.HasOne("FitnessTracker.Models.Goal", "Goal")
                        .WithMany()
                        .HasForeignKey("GoalId");

                    b.HasOne("FitnessTracker.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Goal");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("FitnessTracker.Models.UserTraining", b =>
                {
                    b.HasOne("FitnessTracker.Models.Training", "Training")
                        .WithMany()
                        .HasForeignKey("TrainingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitnessTracker.Models.User", null)
                        .WithMany("UserTraining")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Training");
                });

            modelBuilder.Entity("FitnessTracker.Models.ExerciseHistory", b =>
                {
                    b.Navigation("ExerciseHistoryStats");
                });

            modelBuilder.Entity("FitnessTracker.Models.User", b =>
                {
                    b.Navigation("ExerciseHistories");

                    b.Navigation("TrainingHistories");

                    b.Navigation("UserTraining");
                });
#pragma warning restore 612, 618
        }
    }
}
